'use client'

import { useState } from 'react'

// ── Data types (mirrors Supabase's table editor) ──────────────────────────────
export const PG_TYPES = [
  { label: 'uuid',         value: 'uuid',                    description: 'Unique identifier' },
  { label: 'text',         value: 'text',                    description: 'Unlimited text' },
  { label: 'varchar',      value: 'character varying',       description: 'Variable-length text' },
  { label: 'int4',         value: 'integer',                 description: '4-byte integer' },
  { label: 'int8',         value: 'bigint',                  description: '8-byte integer' },
  { label: 'int2',         value: 'smallint',                description: '2-byte integer' },
  { label: 'float8',       value: 'double precision',        description: '8-byte float' },
  { label: 'numeric',      value: 'numeric',                 description: 'Arbitrary precision' },
  { label: 'bool',         value: 'boolean',                 description: 'True / False' },
  { label: 'date',         value: 'date',                    description: 'Date only' },
  { label: 'timestamptz',  value: 'timestamp with time zone',description: 'Date + time + timezone' },
  { label: 'timestamp',    value: 'timestamp without time zone', description: 'Date + time' },
  { label: 'time',         value: 'time without time zone',  description: 'Time only' },
  { label: 'jsonb',        value: 'jsonb',                   description: 'JSON (binary, indexed)' },
  { label: 'json',         value: 'json',                    description: 'JSON (text)' },
  { label: 'text[]',       value: 'text[]',                  description: 'Array of text' },
  { label: 'int4[]',       value: 'integer[]',               description: 'Array of integers' },
]

// Suggested defaults per type
const TYPE_DEFAULTS: Record<string, { label: string; value: string }[]> = {
  uuid:                         [{ label: 'gen_random_uuid()', value: 'gen_random_uuid()' }],
  'timestamp with time zone':   [{ label: 'now()', value: 'now()' }, { label: 'timezone(utc, now())', value: "timezone('utc'::text, now())" }],
  'timestamp without time zone':[{ label: 'now()', value: 'now()' }],
  boolean:                      [{ label: 'true', value: 'true' }, { label: 'false', value: 'false' }],
  integer:                      [{ label: '0', value: '0' }],
  bigint:                       [{ label: '0', value: '0' }],
  text:                         [{ label: "''  (empty string)", value: "''" }],
}

export interface ColumnDef {
  id: string            // local UI id only
  name: string
  type: string
  defaultValue: string
  isNullable: boolean
  isPrimaryKey: boolean
  isUnique: boolean
  isIdentity: boolean   // bigint auto-increment
}

function makeCol(overrides: Partial<ColumnDef> = {}): ColumnDef {
  return {
    id: Math.random().toString(36).slice(2),
    name: '',
    type: 'text',
    defaultValue: '',
    isNullable: true,
    isPrimaryKey: false,
    isUnique: false,
    isIdentity: false,
    ...overrides,
  }
}

const DEFAULT_COLUMNS: ColumnDef[] = [
  {
    id: 'id',
    name: 'id',
    type: 'uuid',
    defaultValue: 'gen_random_uuid()',
    isNullable: false,
    isPrimaryKey: true,
    isUnique: false,
    isIdentity: false,
  },
  {
    id: 'created_at',
    name: 'created_at',
    type: 'timestamp with time zone',
    defaultValue: 'now()',
    isNullable: true,
    isPrimaryKey: false,
    isUnique: false,
    isIdentity: false,
  },
]

// ── Build CREATE TABLE SQL from column definitions ────────────────────────────
function buildCreateTableSQL(schema: string, tableName: string, columns: ColumnDef[]): string {
  const lines: string[] = []

  for (const col of columns) {
    if (!col.name.trim()) continue

    let line = `  "${col.name}" ${col.type}`

    if (col.isIdentity) {
      line += ' generated by default as identity'
    }

    if (!col.isNullable) line += ' NOT NULL'
    if (col.isPrimaryKey) line += ' PRIMARY KEY'
    else if (col.isUnique) line += ' UNIQUE'
    if (col.defaultValue.trim()) line += ` DEFAULT ${col.defaultValue}`

    lines.push(line)
  }

  return `CREATE TABLE "${schema}"."${tableName}" (\n${lines.join(',\n')}\n);`
}

// ── Type icon ─────────────────────────────────────────────────────────────────
function TypeIcon({ type }: { type: string }) {
  const icons: Record<string, string> = {
    uuid: '🔑', text: 'T', 'character varying': 'T', integer: '#', bigint: '#',
    smallint: '#', 'double precision': '~', numeric: '~', boolean: '◉',
    date: '📅', 'timestamp with time zone': '🕐', 'timestamp without time zone': '🕐',
    jsonb: '{}', json: '{}', 'text[]': '[]', 'integer[]': '[]',
  }
  const icon = icons[type] ?? '?'
  return (
    <span className="inline-flex items-center justify-center w-5 h-5 rounded bg-surface text-xs text-gray-400 font-mono flex-shrink-0">
      {icon}
    </span>
  )
}

// ── Single column row ─────────────────────────────────────────────────────────
function ColumnRow({
  col,
  isFirst,
  onChange,
  onRemove,
}: {
  col: ColumnDef
  isFirst: boolean
  onChange: (updated: ColumnDef) => void
  onRemove: () => void
}) {
  const [showOptions, setShowOptions] = useState(false)
  const suggestions = TYPE_DEFAULTS[col.type] ?? []

  const set = (patch: Partial<ColumnDef>) => onChange({ ...col, ...patch })

  return (
    <div className={`border border-border rounded-md mb-2 ${col.isPrimaryKey ? 'border-accent/30 bg-accent/5' : 'bg-background'}`}>
      {/* Main row */}
      <div className="flex items-center gap-2 px-3 py-2.5">
        <TypeIcon type={col.type} />

        {/* Column name */}
        <input
          className="input text-xs py-1 flex-1 min-w-0"
          placeholder="column_name"
          value={col.name}
          onChange={(e) => set({ name: e.target.value.replace(/\s+/g, '_').toLowerCase() })}
        />

        {/* Type selector */}
        <select
          className="input text-xs py-1 w-36"
          value={col.type}
          onChange={(e) => {
            const newType = e.target.value
            const newSuggestions = TYPE_DEFAULTS[newType] ?? []
            set({
              type: newType,
              defaultValue: newSuggestions[0]?.value ?? '',
              isIdentity: false,
            })
          }}
        >
          {PG_TYPES.map((t) => (
            <option key={t.value} value={t.value}>{t.label}</option>
          ))}
        </select>

        {/* Default value */}
        <div className="relative w-40">
          <input
            className="input text-xs py-1 w-full pr-6"
            placeholder="Default value"
            value={col.defaultValue}
            onChange={(e) => set({ defaultValue: e.target.value })}
            list={`defaults-${col.id}`}
          />
          {suggestions.length > 0 && (
            <datalist id={`defaults-${col.id}`}>
              {suggestions.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}
            </datalist>
          )}
        </div>

        {/* Nullable toggle */}
        <button
          onClick={() => set({ isNullable: !col.isNullable })}
          title="Allow NULL values"
          className={`text-xs px-1.5 py-1 rounded border transition-colors flex-shrink-0 ${
            col.isNullable
              ? 'border-border text-gray-500 hover:border-gray-500'
              : 'border-accent/40 text-accent bg-accent/10'
          }`}
        >
          {col.isNullable ? 'NULL' : 'NOT NULL'}
        </button>

        {/* Options toggle */}
        <button
          onClick={() => setShowOptions((v) => !v)}
          title="More options"
          className="text-gray-500 hover:text-white transition-colors flex-shrink-0"
        >
          <svg className={`w-4 h-4 transition-transform ${showOptions ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
          </svg>
        </button>

        {/* Remove */}
        {!isFirst && (
          <button onClick={onRemove} className="text-gray-600 hover:text-danger transition-colors flex-shrink-0">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        )}
      </div>

      {/* Expanded options */}
      {showOptions && (
        <div className="px-3 pb-3 pt-1 flex flex-wrap gap-3 border-t border-border/50">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              className="accent-accent"
              checked={col.isPrimaryKey}
              onChange={(e) => set({ isPrimaryKey: e.target.checked, isUnique: false, isNullable: e.target.checked ? false : col.isNullable })}
            />
            <span className="text-xs text-gray-300">Primary Key</span>
          </label>

          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              className="accent-accent"
              checked={col.isUnique}
              disabled={col.isPrimaryKey}
              onChange={(e) => set({ isUnique: e.target.checked })}
            />
            <span className={`text-xs ${col.isPrimaryKey ? 'text-gray-600' : 'text-gray-300'}`}>Unique</span>
          </label>

          {(col.type === 'integer' || col.type === 'bigint' || col.type === 'smallint') && (
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                className="accent-accent"
                checked={col.isIdentity}
                onChange={(e) => set({ isIdentity: e.target.checked, defaultValue: e.target.checked ? '' : col.defaultValue })}
              />
              <span className="text-xs text-gray-300">Auto-increment (Identity)</span>
            </label>
          )}
        </div>
      )}
    </div>
  )
}

// ── Main modal ────────────────────────────────────────────────────────────────
interface CreateTableModalProps {
  schema: string          // project slug (PostgreSQL schema name)
  projectId: string
  onClose: () => void
  onCreated: (tableName: string) => void
  runSql: (sql: string) => Promise<{ rows: unknown[]; rowCount: number }>
}

export function CreateTableModal({ schema, onClose, onCreated, runSql }: CreateTableModalProps) {
  const [tableName, setTableName] = useState('')
  const [columns, setColumns] = useState<ColumnDef[]>(DEFAULT_COLUMNS)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [previewSQL, setPreviewSQL] = useState(false)

  const updateCol = (id: string, updated: ColumnDef) =>
    setColumns((prev) => prev.map((c) => (c.id === id ? updated : c)))

  const removeCol = (id: string) =>
    setColumns((prev) => prev.filter((c) => c.id !== id))

  const addColumn = () =>
    setColumns((prev) => [...prev, makeCol()])

  const generatedSQL = tableName.trim()
    ? buildCreateTableSQL(schema, tableName.trim(), columns)
    : '-- Enter a table name above'

  const handleCreate = async () => {
    const name = tableName.trim()
    if (!name) { setError('Table name is required'); return }
    if (!/^[a-z][a-z0-9_]*$/.test(name)) {
      setError('Table name must start with a letter and contain only lowercase letters, numbers, underscores')
      return
    }
    const validCols = columns.filter((c) => c.name.trim())
    if (validCols.length === 0) { setError('Add at least one column'); return }

    setLoading(true)
    setError('')
    try {
      await runSql(buildCreateTableSQL(schema, name, validCols))
      // Attach realtime trigger so live updates work immediately
      await runSql(`
        DROP TRIGGER IF EXISTS "notify_realtime_${name}" ON "${schema}"."${name}";
        CREATE TRIGGER "notify_realtime_${name}"
        AFTER INSERT OR UPDATE OR DELETE ON "${schema}"."${name}"
        FOR EACH ROW EXECUTE FUNCTION intrabase_system.notify_realtime();
      `).catch(() => {
        // Non-fatal — table was created, trigger just won't fire
        console.warn('Realtime trigger could not be attached to', name)
      })
      onCreated(name)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to create table')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="bg-surface border border-border rounded-xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border flex-shrink-0">
          <div>
            <h2 className="text-base font-semibold text-white">Create new table</h2>
            <p className="text-xs text-gray-500 mt-0.5">Schema: <code className="text-accent">{schema}</code></p>
          </div>
          <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5">

          {/* Table name */}
          <div className="mb-6">
            <label className="text-xs font-medium text-gray-400 mb-1.5 block">Table Name *</label>
            <input
              className="input font-mono"
              placeholder="e.g. employees, orders, products"
              value={tableName}
              onChange={(e) => setTableName(e.target.value.replace(/\s+/g, '_').toLowerCase())}
              autoFocus
            />
            {tableName && (
              <p className="text-xs text-gray-600 mt-1">
                Full path: <code className="text-gray-400">"{schema}"."{tableName}"</code>
              </p>
            )}
          </div>

          {/* Columns */}
          <div className="mb-4">
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-medium text-gray-400">Columns</label>
              {/* Column headers */}
              <div className="hidden md:flex items-center gap-2 text-xs text-gray-600 pr-8">
                <span className="w-5" />
                <span className="flex-1 min-w-0 w-32">Name</span>
                <span className="w-36">Type</span>
                <span className="w-40">Default Value</span>
                <span className="w-20">Nullable</span>
              </div>
            </div>

            {columns.map((col, i) => (
              <ColumnRow
                key={col.id}
                col={col}
                isFirst={i === 0}
                onChange={(updated) => updateCol(col.id, updated)}
                onRemove={() => removeCol(col.id)}
              />
            ))}

            <button
              onClick={addColumn}
              className="w-full mt-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-md border border-dashed border-border text-gray-500 hover:border-accent hover:text-accent transition-colors text-sm"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.5v15m7.5-7.5h-15" />
              </svg>
              Add column
            </button>
          </div>

          {/* SQL Preview toggle */}
          <div className="mt-4">
            <button
              onClick={() => setPreviewSQL((v) => !v)}
              className="flex items-center gap-2 text-xs text-gray-500 hover:text-white transition-colors"
            >
              <svg className={`w-3.5 h-3.5 transition-transform ${previewSQL ? 'rotate-90' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.25 4.5l7.5 7.5-7.5 7.5" />
              </svg>
              {previewSQL ? 'Hide' : 'Preview'} SQL
            </button>
            {previewSQL && (
              <pre className="mt-2 p-3 rounded-md bg-background border border-border text-xs font-mono text-gray-300 overflow-x-auto whitespace-pre-wrap">
                {generatedSQL}
              </pre>
            )}
          </div>

          {error && (
            <div className="mt-4 p-3 rounded-md bg-danger/10 border border-danger/30 text-danger text-xs">
              {error}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-border flex-shrink-0">
          <button onClick={onClose} className="btn-ghost">Cancel</button>
          <button onClick={handleCreate} disabled={loading || !tableName.trim()} className="btn-primary">
            {loading ? (
              <span className="flex items-center gap-2">
                <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                </svg>
                Creating...
              </span>
            ) : 'Create Table'}
          </button>
        </div>
      </div>
    </div>
  )
}
