'use client'

import { useState, useCallback } from 'react'
import type { Row, ColumnInfo } from '@/lib/types'

interface TableGridProps {
  columns: ColumnInfo[]
  rows: Row[]
  onInsert: (row: Record<string, unknown>) => Promise<void>
  onUpdate: (pkCol: string, pkVal: unknown, data: Record<string, unknown>) => Promise<void>
  onDelete: (pkCol: string, pkVal: unknown) => Promise<void>
  loading?: boolean
}

export function TableGrid({ columns, rows, onInsert, onUpdate, onDelete, loading }: TableGridProps) {
  const pkCol = columns.find((c) => c.isPrimaryKey)?.name ?? columns[0]?.name

  // Editing state: { rowIdx: number | 'new', colName: string }
  const [editingCell, setEditingCell] = useState<{ rowIdx: number | 'new'; col: string } | null>(null)
  const [editValue, setEditValue] = useState('')
  const [newRow, setNewRow] = useState<Record<string, string>>({})
  const [addingRow, setAddingRow] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [confirmDelete, setConfirmDelete] = useState<unknown>(null) // pk value to confirm delete

  const startEdit = (rowIdx: number, col: string, currentVal: unknown) => {
    setEditingCell({ rowIdx, col })
    setEditValue(currentVal == null ? '' : String(currentVal))
  }

  const cancelEdit = () => {
    setEditingCell(null)
    setEditValue('')
  }

  const commitEdit = async (row: Row) => {
    if (!editingCell || editingCell.rowIdx === 'new') return
    const pkVal = row[pkCol]
    setBusy(true)
    setError(null)
    try {
      await onUpdate(pkCol, pkVal, { [editingCell.col]: editValue === '' ? null : editValue })
      setEditingCell(null)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Update failed')
    } finally {
      setBusy(false)
    }
  }

  const handleDelete = async (pkVal: unknown) => {
    if (confirmDelete !== pkVal) {
      setConfirmDelete(pkVal)
      return
    }
    setBusy(true)
    setError(null)
    try {
      await onDelete(pkCol, pkVal)
      setConfirmDelete(null)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Delete failed')
    } finally {
      setBusy(false)
    }
  }

  const handleInsert = async () => {
    setBusy(true)
    setError(null)
    const autoGenerated = new Set(
      columns.filter((c) => c.isPrimaryKey && c.columnDefault !== null).map((c) => c.name)
    )
    try {
      const cleaned = Object.fromEntries(
        Object.entries(newRow).filter(([k, v]) => v !== '' && !autoGenerated.has(k))
      )
      await onInsert(cleaned)
      setNewRow({})
      setAddingRow(false)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Insert failed')
    } finally {
      setBusy(false)
    }
  }

  const displayColumns = columns.slice(0, 12) // cap columns for display

  // Columns that should be editable in the insert form (skip PK cols with defaults — auto-generated)
  const insertableColumns = displayColumns.filter(
    (col) => !(col.isPrimaryKey && col.columnDefault !== null)
  )
  const autoColumns = displayColumns.filter(
    (col) => col.isPrimaryKey && col.columnDefault !== null
  )

  return (
    <div className="flex flex-col h-full">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-surface">
        <div className="flex items-center gap-2">
          <button
            onClick={() => { setAddingRow(true); setNewRow({}) }}
            disabled={addingRow || busy}
            className="btn-primary text-xs py-1.5"
          >
            + Insert Row
          </button>
          {addingRow && (
            <>
              <button onClick={handleInsert} disabled={busy} className="btn-outline text-xs py-1.5">
                {busy ? 'Saving...' : 'Save'}
              </button>
              <button onClick={() => setAddingRow(false)} className="btn-ghost text-xs py-1.5">
                Cancel
              </button>
            </>
          )}
        </div>
        {error && (
          <span className="text-xs text-danger truncate max-w-xs">{error}</span>
        )}
        {loading && <span className="text-xs text-gray-500">Loading...</span>}
      </div>

      {/* Grid */}
      <div className="flex-1 overflow-auto">
        <table className="data-table">
          <thead>
            <tr>
              <th className="w-8"></th>
              {displayColumns.map((col) => (
                <th key={col.name}>
                  <div className="flex items-center gap-1">
                    <span>{col.name}</span>
                    {col.isPrimaryKey && <span className="text-accent text-xs">pk</span>}
                  </div>
                  <div className="text-gray-600 font-normal normal-case tracking-normal">
                    {col.dataType}
                  </div>
                </th>
              ))}
              <th className="w-20">Actions</th>
            </tr>
          </thead>
          <tbody>
            {/* New row input */}
            {addingRow && (
              <tr className="bg-accent/5 border-b-2 border-accent/30">
                <td className="text-center text-accent text-xs">new</td>
                {displayColumns.map((col) => {
                  const isAutoGenerated = col.isPrimaryKey && col.columnDefault !== null
                  return (
                    <td key={col.name}>
                      {isAutoGenerated ? (
                        <span className="text-xs text-gray-600 italic px-1">auto</span>
                      ) : (
                        <input
                          className="w-full bg-background border border-accent/40 rounded px-2 py-1 text-xs text-white focus:outline-none focus:border-accent"
                          placeholder={col.columnDefault ? `default: ${col.columnDefault}` : col.isNullable ? 'null' : ''}
                          value={newRow[col.name] ?? ''}
                          onChange={(e) => setNewRow((r) => ({ ...r, [col.name]: e.target.value }))}
                        />
                      )}
                    </td>
                  )
                })}
                <td></td>
              </tr>
            )}

            {/* Data rows */}
            {rows.length === 0 && !addingRow && (
              <tr>
                <td colSpan={displayColumns.length + 2} className="text-center text-gray-500 py-10">
                  No rows found
                </td>
              </tr>
            )}
            {rows.map((row, rowIdx) => (
              <tr key={rowIdx}>
                <td className="text-center text-gray-600 text-xs">{rowIdx + 1}</td>
                {displayColumns.map((col) => {
                  const isEditing = editingCell?.rowIdx === rowIdx && editingCell.col === col.name
                  const val = row[col.name]
                  return (
                    <td
                      key={col.name}
                      onDoubleClick={() => !col.isPrimaryKey && startEdit(rowIdx, col.name, val)}
                      className={!col.isPrimaryKey ? 'cursor-pointer' : ''}
                      title={!col.isPrimaryKey ? 'Double-click to edit' : ''}
                    >
                      {isEditing ? (
                        <input
                          autoFocus
                          className="w-full bg-background border border-accent rounded px-2 py-0.5 text-xs text-white focus:outline-none"
                          value={editValue}
                          onChange={(e) => setEditValue(e.target.value)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') commitEdit(row)
                            if (e.key === 'Escape') cancelEdit()
                          }}
                          onBlur={() => commitEdit(row)}
                        />
                      ) : (
                        <span className={val == null ? 'text-gray-600 italic' : col.isPrimaryKey ? 'text-accent' : ''}>
                          {val == null ? 'null' : String(val).length > 60 ? String(val).slice(0, 60) + '…' : String(val)}
                        </span>
                      )}
                    </td>
                  )
                })}
                <td>
                  <button
                    onClick={() => handleDelete(row[pkCol])}
                    disabled={busy}
                    className={`text-xs px-2 py-0.5 rounded transition-colors ${
                      confirmDelete === row[pkCol]
                        ? 'bg-danger text-white'
                        : 'text-gray-500 hover:text-danger'
                    }`}
                    title={confirmDelete === row[pkCol] ? 'Click again to confirm' : 'Delete row'}
                  >
                    {confirmDelete === row[pkCol] ? 'Confirm?' : 'Delete'}
                  </button>
                  {confirmDelete === row[pkCol] && (
                    <button
                      onClick={() => setConfirmDelete(null)}
                      className="text-xs text-gray-500 hover:text-white ml-1"
                    >
                      ✕
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
